spring.application.name=comunidad-backend
server.port=8080

#conexion a la BBDD
spring.datasource.url=jdbc:mariadb://database:3306/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=validate

#Conexion al servidor de correo
spring.mail.host=comunidades-mailpit-dev
spring.mail.port=1025
spring.mail.username= 
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

jwt.secret=${JWT_SECRET}

app.upload.dir=/datos/documents/

app.upload.images.dir=/datos/images/

spring.servlet.multipart.max-file-size=15MB

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true