spring.application.name=comunidad-backend
server.port=8081

#conexion a la BBDD
spring.datasource.url=jdbc:mariadb://localhost:3306/comunidad_vecinos
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

#Conexion al servidor de correo
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

jwt.secret=${JWT_SECRET}

app.upload.dir=/var/www/comunidades/documents/

spring.servlet.multipart.max-file-size=15MB